databases:
  - name: festafacil-db

services:
  - type: web
    name: festafacil-api
    env: node
    plan: free
    region: oregon
    rootDir: .
    autoDeploy: true
    buildCommand: npm ci || npm i
    startCommand: node server/index.js
    healthCheckPath: /api/health
    envVars:
      - key: ALLOWED_ORIGIN
        value: https://carolbrandbpro.github.io
      - key: DATABASE_URL
        fromDatabase:
          name: festafacil-db
          property: connectionString
